/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package socket.client.v3;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;

public class App {

    Socket socket;
    BufferedReader br, keyboard;
    BufferedWriter bw;

    class ReadThread implements Runnable {
        @Override
        public void run() {
            while (true) {
                try {
                    String clientInput = br.readLine();
                    System.out.println("받은 메시지 : " + clientInput);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }

    public App() {
        try {
            socket = new Socket("192.168.200.58", 10000);

            bw = new BufferedWriter(
                    new OutputStreamWriter(socket.getOutputStream()));

            br = new BufferedReader(
                    new InputStreamReader(socket.getInputStream()));

            keyboard = new BufferedReader(
                    new InputStreamReader(System.in));

            Thread t1 = new Thread(new ReadThread());
            t1.start();

            while (true) {
                String keyboardInput = keyboard.readLine();
                bw.write(keyboardInput + "\n");
                bw.flush();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public static void main(String[] args) {
        new App();
    }
}
